name: flutter_training_for_spajam
description: flutter training for spajam
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 1.1.0
  cupertino_icons: ^1.0.2
  chat_bubbles: ^1.5.0
  ulid: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
